[options]
addons_path = /opt/odoo/odoo/addons,/opt/odoo/addons,/opt/odoo/addons_custom
data_dir = /var/lib/odoo/data
admin_passwd = $pbkdf2-sha512$600000$EoIw5hxjzFkrBQAgxHjPOQ$/uWl3He/LXEOBor2FnCT.yHWEFD3kVs3OaPM5oaX/ahmK3GdXDObZSnvAnWrvRBcAXzkl7EzhO5LvFwyRv3wyw
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
http_interface = 0.0.0.0
http_port = 8069
gevent_port = 8072
list_db = True
log_level = info
proxy_mode = False
server_wide_modules = base,rpc,web

